# Generated by Django 3.0.4 on 2020-03-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.Tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time_add',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
