# Generated by Django 3.0.4 on 2020-03-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20200327_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.TextField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='pgn',
        ),
        migrations.AddField(
            model_name='game',
            name='pgn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.PGN'),
        ),
    ]
