# Generated by Django 3.0.4 on 2020-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20200330_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='preview',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
