# Generated by Django 3.0.4 on 2020-03-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_game_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='black_player_id',
            new_name='black_player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='pgn_id',
            new_name='pgn',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='white_player_id',
            new_name='white_player',
        ),
    ]
