# Generated by Django 3.0.4 on 2020-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20200330_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
