# Generated by Django 3.0.4 on 2020-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, null=True),
        ),
    ]
