# Generated by Django 3.0.4 on 2020-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, null=True),
        ),
    ]
