# Generated by Django 3.0.4 on 2020-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0003_auto_20200504_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
