# Generated by Django 3.0.5 on 2020-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0004_auto_20200505_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
